"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import HeaderRegister from "@/components/register/header";
import FooterRegister from "@/components/register/Footer";
import Footer from "@/components/footer";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const PathName = usePathname();
  console.log(PathName, "PathName");

  if (PathName === "/register") {
    return (
      <html lang="en">
        <body className="">
          <div className="my-[20px] bg-[#D6D6D6] w-[850px] mx-auto">

         
          <div id="container">
            <HeaderRegister />

            {children}
          </div>
            <FooterRegister />
            </div>
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body>
        <div id="wraper-grey">
          <div className="container">
            <Header slug="Loans2Go" />
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
